import type { Statement } from '../types/statement.interface';

export const STATEMENTS_DUMMY_DATA: readonly Statement[] = [
  { id: 'st-01', number: 1, text: 'Nederland moet voor 2035 minimaal twee nieuwe kerncentrales bouwen om de klimaatdoelen te halen.', category: 'Klimaat & Energie' },
  { id: 'st-02', number: 2, text: 'Hypotheekrenteaftrek afbouwen. De fiscale aftrek van eigen woningrente wordt binnen tien jaar volledig verdwenen.', category: 'Wonen & Bouwen' },
  { id: 'st-03', number: 3, text: 'Eigen risico zorgverzekering. Het verplichte eigen risico op de basisverzekering moet worden afgeschaft.', category: 'Gezondheidszorg' },
  { id: 'st-04', number: 4, text: 'Asielstroom maximum. Er moet een wettelijk maximum (asielplafond) op het aantal toegelaten asielzoekers per jaar.', category: 'Migratie & Asiel' },
  { id: 'st-05', number: 5, text: 'Vermogensbelasting verhogen. Mensen met een vermogen boven één miljoen euro moeten automatisch meer belasting betalen.', category: 'Financiën & Economie' },
  { id: 'st-06', number: 6, text: 'Basisbeurs studenten. De basisbeurs voor alle studenten in het hoger onderwijs moet fors worden verhoogd.', category: 'Onderwijs' },
  { id: 'st-07', number: 7, text: 'Cameratoezicht uitbreiden. Gemeenten moeten meer bevoegdheden krijgen om cameratoezicht in te zetten tegen overlast.', category: 'Veiligheid & Justitie' },
  { id: 'st-08', number: 8, text: 'Referendum herinvoeren. Het bindend correctief referendum moet wettelijk verankerd worden.', category: 'Bestuur & Democratie' },
  { id: 'st-09', number: 9, text: 'Zonnepanelen verplicht. Alle nieuwbouwwoningen moeten standaard met zonnepanelen worden opgeleverd.', category: 'Klimaat & Energie' },
  { id: 'st-10', number: 10, text: 'Sociale huurwoningen. Gemeenten moeten verplicht worden minimaal dertig procent sociale huurwoningen te bouwen.', category: 'Wonen & Bouwen' },
  { id: 'st-11', number: 11, text: 'Eigen bijdrage jeugdzorg. Ouders met een hoog inkomen moeten meebetalen aan jeugdzorg voor hun kind.', category: 'Gezondheidszorg' },
  { id: 'st-12', number: 12, text: 'Kennismigranten beperken. Het aantal kennismigranten dat jaarlijks wordt toegelaten moet worden beperkt.', category: 'Migratie & Asiel' },
  { id: 'st-13', number: 13, text: 'Btw op boodschappen. Het lage btw-tarief op voedingsmiddelen moet volledig worden afgeschaft.', category: 'Financiën & Economie' },
  { id: 'st-14', number: 14, text: 'Kleinere klassen. Het maximumaantal leerlingen per klas in het basisonderwijs moet wettelijk worden verlaagd.', category: 'Onderwijs' },
  { id: 'st-15', number: 15, text: 'Boa\'s bewapenen. Buitengewoon opsporingsambtenaren moeten standaard met pepperspray worden uitgerust.', category: 'Veiligheid & Justitie' },
  { id: 'st-16', number: 16, text: 'Kiesdrempel invoeren. Er moet een kiesdrempel van twee zetels komen voor de Tweede Kamer.', category: 'Bestuur & Democratie' },
  { id: 'st-17', number: 17, text: 'Vleestaks invoeren. Op de aankoop van vlees moet een aparte klimaatbelasting komen.', category: 'Klimaat & Energie' },
  { id: 'st-18', number: 18, text: 'Leegstandsheffing. Eigenaren die woningen langer dan een jaar leeg laten staan moeten een heffing betalen.', category: 'Wonen & Bouwen' },
  { id: 'st-19', number: 19, text: 'Roken verbieden op terrassen. Roken op horecaterrassen moet landelijk worden verboden.', category: 'Gezondheidszorg' },
  { id: 'st-20', number: 20, text: 'Gezinshereniging beperken. De termijn voor gezinshereniging van statushouders moet worden verlengd.', category: 'Migratie & Asiel' },
  { id: 'st-21', number: 21, text: 'Zzp\'ers verplicht verzekeren. Zelfstandigen zonder personeel moeten verplicht een arbeidsongeschiktheidsverzekering afsluiten.', category: 'Financiën & Economie' },
  { id: 'st-22', number: 22, text: 'Praktijkonderwijs versterken. Er moet meer geld naar praktijkgericht beroepsonderwijs in plaats van universiteiten.', category: 'Onderwijs' },
  { id: 'st-23', number: 23, text: 'Taakstraffen beperken. Voor geweldsdelicten mag geen taakstraf meer worden opgelegd.', category: 'Veiligheid & Justitie' },
  { id: 'st-24', number: 24, text: 'Digitaal stemmen. Nederlanders moeten bij verkiezingen ook digitaal kunnen stemmen.', category: 'Bestuur & Democratie' },
  { id: 'st-25', number: 25, text: 'Snelheidslimiet snelwegen. De maximumsnelheid op snelwegen moet overdag terug naar honderd kilometer per uur.', category: 'Klimaat & Energie' },
  { id: 'st-26', number: 26, text: 'Huurverhoging maximeren. De jaarlijkse huurverhoging in de vrije sector moet wettelijk worden gemaximeerd.', category: 'Wonen & Bouwen' },
  { id: 'st-27', number: 27, text: 'Mentale zorg toegankelijker. De wachtlijsten in de geestelijke gezondheidszorg moeten met voorrang worden weggewerkt.', category: 'Gezondheidszorg' },
  { id: 'st-28', number: 28, text: 'Grenscontroles herinvoeren. Nederland moet tijdelijke grenscontroles kunnen instellen bij hoge asielinstroom.', category: 'Migratie & Asiel' },
  { id: 'st-29', number: 29, text: 'Staatsschuld verlagen. Begrotingsoverschotten moeten verplicht worden ingezet om de staatsschuld af te lossen.', category: 'Financiën & Economie' },
  { id: 'st-30', number: 30, text: 'Burgerschapsonderwijs verplichten. Scholen moeten verplicht structureel aandacht besteden aan burgerschapsvorming.', category: 'Onderwijs' },
];
